# -*- coding: utf-8 -*-
"""phase 7(risk category calculation).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FLO2p-EzqM7U5CGEHdamj56JgggGl3Xa
"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Phase 7 : Risk Category Classification

def risk_category(final_risk):

    if final_risk < 0.25:
        return "SAFE (Legitimate)"

    elif final_risk < 0.50:
        return "SUSPICIOUS (Possible Spam)"

    elif final_risk < 0.75:
        return "HIGH RISK (Possible Phishing)"

    else:
        return "CRITICAL RISK (Highly Likely Phishing)"


# Example risk score (replace with Phase 6 output)
final_risk_score = 0.769

# Apply classification
risk_level = risk_category(final_risk_score)

print("\n----- PHASE 7 : RISK LEVEL INTERPRETATION -----")
print("Final Risk Score :", final_risk_score)
print("Risk Category    :", risk_level)
print("-----------------------------------------------")

