# -*- coding: utf-8 -*-
"""phase 5 (trust score).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqHHqSCZCZD50JhEwsTKAn6UhslxvMxd

The goal is to assign a trust score to every prediction so the system does not only say:

Legitimate

Spam

Phishing

but also indicates how trustworthy that decision is.
"""

from google.colab import drive

drive.mount('/content/drive')

import os

folder_path = "/content/drive/MyDrive/phishing_project_datasets"

print("Files inside phishing_project_datasets:\n")

for file in os.listdir(folder_path):
    print(file)

# Load Trained Models

import joblib
import tensorflow as tf

print("Loading trained models...")

# Load Random Forest model
rf_model = joblib.load("/content/drive/MyDrive/phishing_project_datasets/rf_phishing_model.pkl")

# Load BiLSTM model
bilstm_model = tf.keras.models.load_model("/content/drive/MyDrive/phishing_project_datasets/bilstm_email_model.h5")

print("Random Forest Model Loaded Successfully")
print("BiLSTM Model Loaded Successfully")

"""These will be used to compute:

Model Confidence → Trust Score
"""

# Load Test Data and Tokenizer

import joblib

print("Loading test datasets...")

# Load tokenizer
tokenizer = joblib.load("/content/drive/MyDrive/phishing_project_datasets/tokenizer.pkl")

# Load BiLSTM test sequences
X_test_seq = joblib.load("/content/drive/MyDrive/phishing_project_datasets/X_test_seq.pkl")

# Load Random Forest test features
X_test_url = joblib.load("/content/drive/MyDrive/phishing_project_datasets/X_test_url.pkl")

# Load labels
y_test = joblib.load("/content/drive/MyDrive/phishing_project_datasets/y_test.pkl")

print("Tokenizer Loaded")
print("BiLSTM Test Data Loaded:", X_test_seq.shape)
print("RF Test Data Loaded:", X_test_url.shape)
print("Labels Loaded:", y_test.shape)

"""The test samples are not aligned.

BiLSTM has 39154 samples while RF and labels have 49590 samples.

If we continue like this, Phase 5 will fail when we combine predictions.

So we will safely align the datasets by using the minimum size.
"""

# Align Test Data Sizes

print("Aligning test datasets...")

# Find minimum size
min_size = min(len(X_test_seq), len(X_test_url), len(y_test))

# Trim datasets to same size
X_test_seq = X_test_seq[:min_size]
X_test_url = X_test_url[:min_size]
y_test = y_test[:min_size]

print("Datasets aligned successfully")

print("BiLSTM test shape:", X_test_seq.shape)
print("RF test shape:", X_test_url.shape)
print("Labels shape:", y_test.shape)

"""Here we will extract confidence scores from both models.

Instead of just predicting class labels, we obtain probabilities, which will later be used for the trust score formula.
"""

# Generate Prediction Probabilities

import numpy as np

print("Generating prediction probabilities...")

# Random Forest probabilities
rf_probs = rf_model.predict_proba(X_test_url)

# BiLSTM probabilities
bilstm_probs = bilstm_model.predict(X_test_seq)

print("RF probabilities shape:", rf_probs.shape)
print("BiLSTM probabilities shape:", bilstm_probs.shape)

"""Now the system has:

RF probabilities
BiLSTM probabilities

These will allow us to compute:

Confidence score
Model agreement
Trust score

which is the core idea of your research paper.

Extract Confidence Scores

Now we extract the actual confidence values.

For Random Forest:

Column 1 = probability of phishing.

For BiLSTM:

The output itself is the phishing probability.
"""

# Extract Model Confidence Scores

print("Extracting confidence scores...")

# RF confidence (probability of phishing)
rf_confidence = rf_probs[:, 1]

# BiLSTM confidence
bilstm_confidence = bilstm_probs.flatten()

print("RF confidence sample:", rf_confidence[:5])
print("BiLSTM confidence sample:", bilstm_confidence[:5])

"""What We Have Now

For each email/URL we now have:

RF confidence
BiLSTM confidence

Next we will compute:

Model Agreement

Example:

RF	BiLSTM	Agreement
Phishing	Phishing	1
Legitimate	Legitimate	1
Different		0

This will become part of your Trust Score formula.
"""

#Convert Probabilities to Predictions

print("Converting probabilities to predictions...")

# RF predictions
rf_pred = (rf_confidence >= 0.5).astype(int)

# BiLSTM predictions
bilstm_pred = (bilstm_confidence >= 0.5).astype(int)

print("RF prediction sample:", rf_pred[:10])
print("BiLSTM prediction sample:", bilstm_pred[:10])

# Calculate Model Agreement

print("Calculating model agreement...")

# Agreement = 1 if both models give same prediction
agreement = (rf_pred == bilstm_pred).astype(int)

print("Agreement sample:", agreement[:10])

# Check percentage agreement
agreement_rate = agreement.mean()

print("Overall Agreement Rate:", round(agreement_rate * 100, 2), "%")

"""system now has:

RF confidence
BiLSTM confidence
RF prediction
BiLSTM prediction
Model agreement

These are the 3 components needed for the trust formula.
"""

# Compute Hybrid Confidence

print("Computing hybrid confidence...")

# Average confidence of both models
hybrid_confidence = (rf_confidence + bilstm_confidence) / 2

print("Hybrid confidence sample:", hybrid_confidence[:10])

"""system now has:

RF confidence
BiLSTM confidence
Hybrid confidence
Model agreement

These are two main inputs for the Trust Score.

In the next step compute the actual Trust Score (0–10 scale).

Example output your system will produce:

Prediction: Phishing
Confidence: 0.93
Agreement: 1
Trust Score: 8.7 / 10
Risk Level: High

This is the main novelty of the project.
"""

#Compute Trust Score

print("Calculating trust scores...")

alpha = 0.6
beta = 0.4

# Explanation factor (temporary constant)
explanation_factor = 1

# Trust score (0-1 scale)
trust_raw = (alpha * hybrid_confidence) + (beta * agreement)

# Convert to 0–10 scale
trust_score = trust_raw * 10

print("Trust score sample:", trust_score[:10])

"""Now we make the output human-readable
| Trust Score | Risk Level   |
| ----------- | ------------ |
| **0 – 3**   | Low Trust    |
| **3 – 7**   | Medium Trust |
| **7 – 10**  | High Trust   |

"""

#Convert Trust Score to Risk Level


print("Generating risk levels...")

risk_levels = []

for score in trust_score:

    if score < 3:
        risk_levels.append("Low Trust")

    elif score < 7:
        risk_levels.append("Medium Trust")

    else:
        risk_levels.append("High Trust")

print("Sample Risk Levels:", risk_levels[:10])

