# -*- coding: utf-8 -*-
"""phase 8(domain reputation security signals).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBgiCg8VZSce_mTYMRJHH_Mm84OEKI1p

introduces external security intelligence signals to strengthen detection.

Domain Reputation

Check if a domain is:

newly registered

blacklisted

suspicious

URL Input
   ↓
Feature Engineering
   ↓
ML Model
   ↓
Trust Score
   ↓
Hybrid Risk Score
   ↓
Risk Category
   ↓
Domain Reputation Check
   ↓
Final Security Verdict
"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# =====================================================
# PHASE 8 : DOMAIN REPUTATION & SECURITY SIGNALS
# =====================================================

import re
from urllib.parse import urlparse

print("\n----- PHASE 8 : DOMAIN REPUTATION ANALYSIS -----")

# Example URL to test
url = input("Enter URL to analyze: ")

parsed = urlparse(url)
domain = parsed.netloc

print("\nAnalyzing domain:", domain)


# ------------------------------------------
# SECURITY SIGNAL FUNCTIONS
# ------------------------------------------

def has_https(url):
    return url.startswith("https")


def url_length(url):
    return len(url)


def contains_ip(domain):
    ip_pattern = r"\d+\.\d+\.\d+\.\d+"
    return bool(re.match(ip_pattern, domain))


def contains_at_symbol(url):
    return "@" in url


def count_subdomains(domain):
    return domain.count(".")


def contains_double_slash(url):
    return url.count("//") > 1


# ------------------------------------------
# SIGNAL ANALYSIS
# ------------------------------------------

https_signal = has_https(url)
length_signal = url_length(url)
ip_signal = contains_ip(domain)
at_signal = contains_at_symbol(url)
subdomain_count = count_subdomains(domain)
double_slash_signal = contains_double_slash(url)


# ------------------------------------------
# DOMAIN REPUTATION SCORING
# ------------------------------------------

reputation_score = 0


# HTTPS check
if https_signal:
    reputation_score += 2
else:
    reputation_score -= 2


# URL length check
if length_signal > 75:
    reputation_score -= 2
elif length_signal > 50:
    reputation_score -= 1
else:
    reputation_score += 1


# IP address usage
if ip_signal:
    reputation_score -= 3


# '@' symbol
if at_signal:
    reputation_score -= 2


# many subdomains
if subdomain_count > 3:
    reputation_score -= 2
else:
    reputation_score += 1


# double slash trick
if double_slash_signal:
    reputation_score -= 1


# ------------------------------------------
# REPUTATION LEVEL
# ------------------------------------------

if reputation_score >= 3:
    reputation_level = "SAFE DOMAIN"

elif reputation_score >= 0:
    reputation_level = "SUSPICIOUS DOMAIN"

else:
    reputation_level = "HIGHLY SUSPICIOUS DOMAIN"


# ------------------------------------------
# RESULTS
# ------------------------------------------

print("\n----- DOMAIN SECURITY SIGNALS -----")

print("HTTPS Present          :", https_signal)
print("URL Length             :", length_signal)
print("Uses IP Address        :", ip_signal)
print("Contains '@' Symbol    :", at_signal)
print("Subdomain Count        :", subdomain_count)
print("Double Slash Trick     :", double_slash_signal)

print("\nDomain Reputation Score :", reputation_score)
print("Domain Reputation Level :", reputation_level)

print("-----------------------------------")

"""Advanced version"""

# =====================================================
# PHASE 8 : DOMAIN REPUTATION & ADVANCED SECURITY SIGNALS
# =====================================================

import re
from urllib.parse import urlparse

print("\n----- PHASE 8 : DOMAIN REPUTATION ANALYSIS (UPGRADED) -----")

url = input("Enter URL to analyze: ")

parsed = urlparse(url)
domain = parsed.netloc.lower()

print("\nAnalyzing domain:", domain)


# -----------------------------------------------------
# SUSPICIOUS KEYWORDS & BRAND LIST
# -----------------------------------------------------

brand_keywords = [
    "paypal","apple","icloud","amazon","bank","google",
    "facebook","microsoft","netflix","whatsapp"
]

suspicious_keywords = [
    "login","verify","secure","update","account",
    "signin","confirm","password","billing"
]


# -----------------------------------------------------
# SECURITY SIGNAL FUNCTIONS
# -----------------------------------------------------

def has_https(url):
    return url.startswith("https")


def url_length(url):
    return len(url)


def contains_ip(domain):
    ip_pattern = r"\d+\.\d+\.\d+\.\d+"
    return bool(re.match(ip_pattern, domain))


def contains_at_symbol(url):
    return "@" in url


def count_subdomains(domain):
    return domain.count(".")


def contains_double_slash(url):
    return url.count("//") > 1


def has_hyphen(domain):
    return "-" in domain


def contains_digits(domain):
    return any(char.isdigit() for char in domain)


def brand_impersonation(domain):
    for brand in brand_keywords:
        if brand in domain:
            return True
    return False


def suspicious_word(domain):
    for word in suspicious_keywords:
        if word in domain:
            return True
    return False


# -----------------------------------------------------
# SIGNAL ANALYSIS
# -----------------------------------------------------

https_signal = has_https(url)
length_signal = url_length(url)
ip_signal = contains_ip(domain)
at_signal = contains_at_symbol(url)
subdomain_count = count_subdomains(domain)
double_slash_signal = contains_double_slash(url)
hyphen_signal = has_hyphen(domain)
digit_signal = contains_digits(domain)
brand_signal = brand_impersonation(domain)
keyword_signal = suspicious_word(domain)


# -----------------------------------------------------
# DOMAIN REPUTATION SCORING
# -----------------------------------------------------

reputation_score = 0


# HTTPS check
if https_signal:
    reputation_score += 2
else:
    reputation_score -= 2


# URL length
if length_signal > 75:
    reputation_score -= 2
elif length_signal > 50:
    reputation_score -= 1
else:
    reputation_score += 1


# IP address
if ip_signal:
    reputation_score -= 3


# '@' symbol
if at_signal:
    reputation_score -= 2


# Subdomain abuse
if subdomain_count > 3:
    reputation_score -= 2
else:
    reputation_score += 1


# Double slash trick
if double_slash_signal:
    reputation_score -= 1


# Hyphen phishing
if hyphen_signal:
    reputation_score -= 1


# Digit-heavy domains
if digit_signal:
    reputation_score -= 1


# Brand impersonation
if brand_signal:
    reputation_score -= 2


# Suspicious keywords
if keyword_signal:
    reputation_score -= 1


# -----------------------------------------------------
# REPUTATION LEVEL
# -----------------------------------------------------

if reputation_score >= 3:
    reputation_level = "SAFE DOMAIN"

elif reputation_score >= 0:
    reputation_level = "SUSPICIOUS DOMAIN"

else:
    reputation_level = "HIGHLY SUSPICIOUS DOMAIN"


# -----------------------------------------------------
# OUTPUT RESULTS
# -----------------------------------------------------

print("\n----- DOMAIN SECURITY SIGNALS -----")

print("HTTPS Present            :", https_signal)
print("URL Length               :", length_signal)
print("Uses IP Address          :", ip_signal)
print("Contains '@' Symbol      :", at_signal)
print("Subdomain Count          :", subdomain_count)
print("Double Slash Trick       :", double_slash_signal)
print("Hyphen In Domain         :", hyphen_signal)
print("Contains Digits          :", digit_signal)
print("Brand Impersonation      :", brand_signal)
print("Suspicious Keyword Found :", keyword_signal)

print("\nDomain Reputation Score  :", reputation_score)
print("Domain Reputation Level  :", reputation_level)

print("-----------------------------------")

