# -*- coding: utf-8 -*-
"""phase 3 (hybrid mode).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BNuGtqJJBqnWUlpOl8B7KJ2GZAkEbe9X
"""

!pip install joblib -quite
!pip install tensorflow -quite

from google.colab import drive
drive.mount('/content/drive')

# LOAD LIBRARIES AND SAVED MODELS


import numpy as np
import joblib
import pickle
from tensorflow.keras.models import load_model

print("Loading models...")

# Load Random Forest model
rf_model = joblib.load("/content/drive/MyDrive/phishing_project_datasets/rf_phishing_model.pkl")

# Load BiLSTM model
bilstm_model = load_model("/content/drive/MyDrive/phishing_project_datasets/bilstm_email_model.h5")

print("Models loaded successfully.")

# LOAD TOKENIZER

print("Loading tokenizer...")

import pickle

with open("/content/drive/MyDrive/phishing_project_datasets/tokenizer.pkl", "rb") as f:
    tokenizer = pickle.load(f)

print("Tokenizer loaded successfully.")

"""Convert Email Text → Sequence (BiLSTM Input)
🎯 Aim

Deep learning models cannot read text directly.
So we convert the email sentence into numerical tokens using the tokenizer and then pad it to a fixed length.
"""

# TEXT → SEQUENCE CONVERSION

from tensorflow.keras.preprocessing.sequence import pad_sequences

# maximum length used during training
max_length = 200

# Sample email for testing
email_text = "Dear user your account has been suspended please click the link below to verify your account immediately"

print("Email Text:")
print(email_text)

# Convert text to sequence
sequence = tokenizer.texts_to_sequences([email_text])

# Apply padding
padded_sequence = pad_sequences(sequence, maxlen=max_length)

print("\nTokenized Sequence:")
print(sequence)

print("\nPadded Sequence Shape:")
print(padded_sequence.shape)

"""Get Prediction from BiLSTM Model
🎯 Aim

Use the BiLSTM model to predict probabilities for the three classes:
"""

# BILSTM PREDICTION

# Get prediction from BiLSTM
bilstm_prediction = bilstm_model.predict(padded_sequence)

print("BiLSTM Raw Prediction:")
print(bilstm_prediction)

# Convert to readable format
classes = ["Legitimate", "Spam", "Phishing"]

print("\nClass Probabilities:")

for i, prob in enumerate(bilstm_prediction[0]):
    print(f"{classes[i]}: {prob:.4f}")

"""since we recive binary outbut we now convert them to this model textual"""

# (CORRECTED FOR BINARY MODEL)

#BILSTM Prediction


bilstm_prediction = bilstm_model.predict(padded_sequence)

prob = bilstm_prediction[0][0]

print("BiLSTM Probability:", prob)

if prob > 0.5:
    print("BiLSTM Prediction: Phishing")
else:
    print("BiLSTM Prediction: Legitimate")

"""Use the Random Forest model to classify the email into:

Legitimate
Spam
Phishing

⚠ Important
Random Forest does not use raw text. It expects structured features (like the ones used in Phase 1).

For now we will simulate feature input just to confirm the model works. Later we will connect it properly.
"""

# RANDOM FOREST PREDICTION
import numpy as np

# Example dummy features (replace later with real features)
rf_input = np.random.rand(1, rf_model.n_features_in_)

# Get probabilities
rf_prediction = rf_model.predict_proba(rf_input)

print("Random Forest Raw Prediction:")
print(rf_prediction)

classes = ["Legitimate", "Spam", "Phishing"]

print("\nClass Probabilities:")

for i, prob in enumerate(rf_prediction[0]):
    print(f"{classes[i]}: {prob:.4f}")

#HYBRID MODEL FUSION

# Random Forest probability
rf_prob = rf_prediction[0][1]

# BiLSTM probability
bilstm_prob = bilstm_prediction[0][0]

print("Random Forest Phishing Probability:", rf_prob)
print("BiLSTM Phishing Probability:", bilstm_prob)

# Hybrid weights
rf_weight = 0.4
bilstm_weight = 0.6

# Hybrid fusion
final_prob = (rf_weight * rf_prob) + (bilstm_weight * bilstm_prob)

print("\nHybrid Probability:", final_prob)

# Final decision
if final_prob > 0.5:
    print("Final Prediction: PHISHING")
else:
    print("Final Prediction: LEGITIMATE")