# -*- coding: utf-8 -*-
"""phase 9(Adversarial Testing).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a2agzwShSWe8drzxNj6bZhSYAXcezIoh

Adversarial testing checks how robust your phishing detection system is when attackers try to trick it.

Phishers often modify URLs slightly to bypass security systems.

| Legitimate | Adversarial Phishing    |
| ---------- | ----------------------- |
| paypal.com | paypa1.com              |
| amazon.com | amaz0n-login.com        |
| google.com | secure-google-login.net |

These are called evasion attacks.

Your system must still detect them.
"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# ------------------------------------------------------------
# PHASE 9 : ADVERSARIAL ROBUSTNESS TESTING
# Trust-Aware Hybrid Explainable AI Phishing Detection
# ------------------------------------------------------------

import re
import numpy as np
import pandas as pd
from urllib.parse import urlparse
import math

print("----- PHASE 9 : ADVERSARIAL ROBUSTNESS TESTING -----")


# ------------------------------------------------------------
# Feature Extraction (same logic used in previous phases)
# ------------------------------------------------------------

def extract_features(url):

    parsed = urlparse(url)

    domain = parsed.netloc
    path = parsed.path

    features = {}

    # URL length
    features["url_length"] = len(url)

    # HTTPS presence
    features["https"] = 1 if "https" in url else 0

    # IP address detection
    features["ip_address"] = 1 if re.search(r'\d+\.\d+\.\d+\.\d+', url) else 0

    # @ symbol
    features["at_symbol"] = 1 if "@" in url else 0

    # number of subdomains
    features["subdomain_count"] = domain.count(".")

    # hyphen in domain
    features["hyphen_domain"] = 1 if "-" in domain else 0

    # suspicious keywords
    suspicious_words = [
        "login","verify","secure","account","update",
        "bank","confirm","password","signin","validate"
    ]

    features["suspicious_keywords"] = sum(word in url.lower() for word in suspicious_words)

    # brand impersonation keywords
    brand_words = [
        "paypal","amazon","google","apple","microsoft",
        "bank","netflix","facebook","instagram"
    ]

    features["brand_keywords"] = sum(word in url.lower() for word in brand_words)

    # entropy-like randomness check
    probabilities = [url.count(c)/len(url) for c in set(url)]
    entropy = -sum(p * math.log2(p) for p in probabilities)

    features["url_entropy"] = entropy

    return pd.DataFrame([features])


# ------------------------------------------------------------
# Simple Trust Score Logic (same concept as Phase 5)
# ------------------------------------------------------------

def compute_trust_score(features):

    score = 10

    if features["ip_address"].values[0] == 1:
        score -= 3

    if features["at_symbol"].values[0] == 1:
        score -= 2

    if features["hyphen_domain"].values[0] == 1:
        score -= 1

    if features["suspicious_keywords"].values[0] > 0:
        score -= 2

    if features["brand_keywords"].values[0] > 0:
        score -= 1

    if features["url_length"].values[0] > 75:
        score -= 1

    score = max(score,0)

    trust_score = score / 10

    return trust_score


# ------------------------------------------------------------
# Simulated ML probability (since model may not be loaded here)
# Replace with your trained model if available
# ------------------------------------------------------------

def model_probability(features):

    risk = 0

    if features["ip_address"].values[0] == 1:
        risk += 0.3

    if features["suspicious_keywords"].values[0] > 0:
        risk += 0.2

    if features["brand_keywords"].values[0] > 0:
        risk += 0.2

    if features["url_entropy"].values[0] > 4:
        risk += 0.2

    if features["hyphen_domain"].values[0] == 1:
        risk += 0.1

    return min(risk,1)


# ------------------------------------------------------------
# Hybrid Risk Score (Phase 6 logic)
# ------------------------------------------------------------

def hybrid_score(model_prob, trust_score):

    alpha = 0.7

    final_score = alpha * model_prob + (1 - alpha) * (1 - trust_score)

    return final_score


# ------------------------------------------------------------
# Risk Category (Phase 7 logic)
# ------------------------------------------------------------

def risk_category(score):

    if score >= 0.75:
        return "CRITICAL RISK (Highly Likely Phishing)"

    elif score >= 0.50:
        return "HIGH RISK"

    elif score >= 0.30:
        return "MEDIUM RISK"

    else:
        return "LOW RISK"


# ------------------------------------------------------------
# Adversarial URL Test Set
# ------------------------------------------------------------

adversarial_urls = [

    "http://amaz0n-login-security-update.com",
    "https://secure-paypal-verify-account.com",
    "http://g00gle-account-confirmation.net",
    "http://apple-id-security-login.com",
    "http://bankofamerica-secure-login-update.com",
    "http://paypal.verify-login.security-check.com",
    "http://micr0soft-account-verification.net",
    "http://netflix-billing-update-secure.com",
    "http://instagram-security-login-confirm.com",
    "http://faceb00k-account-warning-login.net"

]


# ------------------------------------------------------------
# Run Adversarial Tests
# ------------------------------------------------------------

for url in adversarial_urls:

    print("\n---------------------------------------------")
    print("Testing URL:", url)

    features = extract_features(url)

    model_prob = model_probability(features)

    trust_score = compute_trust_score(features)

    final_score = hybrid_score(model_prob, trust_score)

    category = risk_category(final_score)

    print("Model Probability :", round(model_prob,3))
    print("Trust Score       :", round(trust_score,3))
    print("Final Risk Score  :", round(final_score,3))
    print("Risk Category     :", category)

    if final_score >= 0.5:
        print("Result : System Successfully Detected Phishing")

    else:
        print("Result : Potential Model Weakness Detected")


print("\n----- ADVERSARIAL TESTING COMPLETED -----")

import matplotlib.pyplot as plt
import numpy as np

# DATA
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
base_paper = [89, 87, 84, 85]
your_model = [96.2, 95.4, 95.9, 95.6]

trust_metrics = ['Trust Score', 'False Positive Rate']
base_trust = [6.8, 12]
your_trust = [9.3, 4]

x = np.arange(len(metrics))
width = 0.35

fig, axs = plt.subplots(1, 2, figsize=(13, 5))

# -------- LEFT GRAPH (FIXED) --------
bars1 = axs[0].bar(x - width/2, base_paper, width,
                   color='#FF6B6B', label='Base Paper')

bars2 = axs[0].bar(x + width/2, your_model, width,
                   color='#4ECDC4', label='Proposed Model')

# Line overlay (optional but powerful)
axs[0].plot(x, your_model, color='#1A535C', marker='o', linewidth=2)

axs[0].set_xticks(x)
axs[0].set_xticklabels(metrics)
axs[0].set_title('Performance Comparison')
axs[0].set_ylabel('Score (%)')
axs[0].legend()

axs[0].grid(axis='y', linestyle='--', alpha=0.5)

# -------- RIGHT GRAPH --------
x2 = np.arange(len(trust_metrics))
width2 = 0.35

axs[1].bar(x2 - width2/2, base_trust, width2,
           color='#FF6B6B', label='Base Paper')

axs[1].bar(x2 + width2/2, your_trust, width2,
           color='#4ECDC4', label='Proposed Model')

axs[1].set_xticks(x2)
axs[1].set_xticklabels(trust_metrics)
axs[1].set_title('Trust & Reliability')
axs[1].legend()

axs[1].grid(axis='y', linestyle='--', alpha=0.5)

fig.suptitle('Phishing Detection Model Dashboard', fontsize=16)

plt.tight_layout()
plt.show()

